### ISSUE TITLE
White screen Jarvis V3 Ipad 4

### ISSUE THREAD

**Issue by braintr84** [Zefau/ioBroker.jarvis#1766]
Hi everyone, i still use an Ipad4 for Jarvis, it is absolutely sufficient for this purpose, anyhow i updated to Jarvis v3 and was only able to see a white screen in safari (ios 10.3.3) loading chrome etc is not possible as IOS is  outdated (but no new IOS version available for this old device). I went back to v2 and received an invalid time stamp error. Is there a a way either to get v2 working again, or to use v3 on Ipad 4 ? Thank you in advance!

**Comment by Zefau** [comment]
Have you tried on a desktop browser?

**Comment by braintr84** [comment]
Hi, yes.. works fine on Desktop and other android Devices, just the IPAD 4 displays a white screen on Jarvis V3... i have not found a solution for this issue. Back to Jarvis V2.x everything works fine, but i get a Time stamp error as soon as i want to change devices etc.

**Comment by Zefau** [comment]
What do you mean by timestamp error? Did you restore a backup when you went back to v2? Your data is converted to the newly v3 structure and going back to v2 requires restoring a backup with valid v2 data.

Regarding the whitescreen I have no idea. Most likely due to the socket upgrade from 2.3.x to 4.3.x, which may not be compatible with iPad 4 (but I don't know).

Did you open jarvis on the iPad from the ioBroker Dashboard to provide all required connection details?

**Comment by braintr84** [comment]
![image](https://user-images.githubusercontent.com/44327780/179207096-23390f86-0232-491a-a146-757143fb3f4e.png)
 
This is the error i get. I know how to delete V3 and install latest V2 version, and it works... but i get above error as soon as i want to change something. 

In the meantime i also tried different things with the ipad4, i set it back ( factory reset ) tried all available browsers ( chrome, firefox, edge, safari) non showed anything when calling Jarvis V3 URL ( Just a white screen)... 

So it seems that there is no way to get an IPAD4 to work with Jarvis V3. I am ok with that as long as i can get V2 to work properly again. 

Once again, thank you for your help!

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/866
