### ISSUE TITLE
collapsible / expandable widgets

### ISSUE THREAD

**Issue by ottk3** [Zefau/ioBroker.jarvis#194]
It would be great to be able to have widgets that could be collapsed by default, like a chart for the temperature curve over time of a room that you don't want to have statically visible.

**Comment by ottk3** [comment]
Duplicate of #190

**Comment by Zefau** [comment]
@ottk3 the referenced issue is for the configuration page and the list of devices. Is that what you meant as well?

**Comment by ottk3** [comment]
Hi @Zefau,

I actually meant as a widget inside a column. re-opened it as a feature request :)

**Comment by Zefau** [comment]
@ottk3 for clarification: You refer to the actual widgets and not the widget configuration, right?

**Comment by ottk3** [comment]
Yes, the main use cases would be to show additional details of a device that I would not like to be always visible (especially on mobile). I got an tab for controlling several radiators and would like to be able to expand charts under each for more details.

**Comment by SevenUp666** [comment]
schließe mich der Anfrage an. Wäre ein praktisches Feature!
Wenn der Zustand (ein/ausgeklappt) auch noch gespeichert wird, dann wäre es ganz cool.

**Comment by Zefau** [comment]
This feature request has to be discussed due to the changed structure of v3. 

v3 uses a grid-layout (instead of v2, which uses a column-layout).
Due to the possibility in v3 that widgets may span across rows and / or columns, it is impossible for other widgets to use the space of an collapsed widget. Thus, collapsing a widget does not make sense anymore, does it?
