### ISSUE TITLE
HM-IP Gerät PSM-2 wird nicht erkannt

### ISSUE THREAD

**Issue by ISharkI** [Zefau/ioBroker.jarvis#2131]
Hallo zusammen,

ich habe hier eine Homematic IP PSM-2 Schalt- und Messsteckdose, die von meiner jarvis-Instanz (v3.1.2) nicht erkannt wird. Sie bittet daher höflich darum das ganze zu melden (und da ich das gerne natürlich im Jarvis hätte). 
[Beigefügt der JSON-Tree als txt-file](https://github.com/Zefau/ioBroker.jarvis/files/10322488/hm-rpc.0.0034DF29A36950.json.txt) für das Objekt aus dem iobroker (iobroker-Version 6.3.5, hm-rega-Version 1.15.16).

Die (für mich) interessantesten Werte aus dem CCU Webinterface sind hier schonmal aufgelistet

Function Socket
```

"HmIP-PSM-2": {
    "temperature":{
        "state":".0.ACTUAL_TEMPERATURE"
        "unit":" °C"
    },
    "power":{
        "state":".2.STATE",
        "action":".3.STATE"
    },
    "powerCurrent":{
        "state":".6.CURRENT",
        "unit":" mA"
    },
    "powerFrequency":{
        "state":".6.FREQUENCY"
    },
    "powerCounter":{
        "state":".6.ENERGY_COUNTER",
        "unit":" Wh"
    },
    "powerMeter":{
        "state":".6.POWER",
        "unit":" W"
    },
    "powerVoltage":{
        "state":".6.VOLTAGE",
        "unit":" V"
    }
}
```

Falls noch mehr input gebraucht wird bitte melden.

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.3-beta.9`

**Comment by Zefau** [comment]
@ISharkI

**Comment by ISharkI** [comment]
Hallo,
sorry für die späte Rückmeldung, das Gerät ist nicht bei mir lokal verbaut. Mit der Beta funktioniert es einwandfrei anzuzeigen.
Danke fürs umsetzen.
Was jetzt noch fehlen würde wäre eine möglichkeit auf null zurückzusetzen. Aber falls ich den JSON Tree verstehe ist das auch im iobroker bisher nicht drin.

**Comment by Yroge** [comment]
Obrigado Michael Mueler.Eu até havia escrito um relato de ocorridos.Mas fica somente o obrigado.Toda a rede.Att. Gregory Vinicius Dadam.Em 3 de mar. de 2023 20:59, Michael Mueller ***@***.***> escreveu:

Hallo,

sorry für die späte Rückmeldung, das Gerät ist nicht bei mir lokal verbaut. Mit der Beta funktioniert es einwandfrei anzuzeigen.

Danke fürs umsetzen.

Was jetzt noch fehlen würde wäre eine möglichkeit auf null zurückzusetzen. Aber falls ich den JSON Tree verstehe ist das auch im iobroker bisher nicht drin.



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Em 3 de mar. de 2023 20:59, Michael Mueller ***@***.***> escreveu:

Hallo,

sorry für die späte Rückmeldung, das Gerät ist nicht bei mir lokal verbaut. Mit der Beta funktioniert es einwandfrei anzuzeigen.

Danke fürs umsetzen.

Was jetzt noch fehlen würde wäre eine möglichkeit auf null zurückzusetzen. Aber falls ich den JSON Tree verstehe ist das auch im iobroker bisher nicht drin.



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Em 3 de mar. de 2023 20:59, Michael Mueller ***@***.***> escreveu:

Hallo,

sorry für die späte Rückmeldung, das Gerät ist nicht bei mir lokal verbaut. Mit der Beta funktioniert es einwandfrei anzuzeigen.

Danke fürs umsetzen.

Was jetzt noch fehlen würde wäre eine möglichkeit auf null zurückzusetzen. Aber falls ich den JSON Tree verstehe ist das auch im iobroker bisher nicht drin.



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Em 3 de mar. de 2023 20:59, Michael Mueller ***@***.***> escreveu:

Hallo,

sorry für die späte Rückmeldung, das Gerät ist nicht bei mir lokal verbaut. Mit der Beta funktioniert es einwandfrei anzuzeigen.

Danke fürs umsetzen.

Was jetzt noch fehlen würde wäre eine möglichkeit auf null zurückzusetzen. Aber falls ich den JSON Tree verstehe ist das auch im iobroker bisher nicht drin.



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Em 3 de mar. de 2023 20:59, Michael Mueller ***@***.***> escreveu:

Hallo,

sorry für die späte Rückmeldung, das Gerät ist nicht bei mir lokal verbaut. Mit der Beta funktioniert es einwandfrei anzuzeigen.

Danke fürs umsetzen.

Was jetzt noch fehlen würde wäre eine möglichkeit auf null zurückzusetzen. Aber falls ich den JSON Tree verstehe ist das auch im iobroker bisher nicht drin.



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Em 3 de mar. de 2023 20:59, Michael Mueller ***@***.***> escreveu:

Hallo,

sorry für die späte Rückmeldung, das Gerät ist nicht bei mir lokal verbaut. Mit der Beta funktioniert es einwandfrei anzuzeigen.

Danke fürs umsetzen.

Was jetzt noch fehlen würde wäre eine möglichkeit auf null zurückzusetzen. Aber falls ich den JSON Tree verstehe ist das auch im iobroker bisher nicht drin.



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Em 3 de mar. de 2023 20:59, Michael Mueller ***@***.***> escreveu:

Hallo,

sorry für die späte Rückmeldung, das Gerät ist nicht bei mir lokal verbaut. Mit der Beta funktioniert es einwandfrei anzuzeigen.

Danke fürs umsetzen.

Was jetzt noch fehlen würde wäre eine möglichkeit auf null zurückzusetzen. Aber falls ich den JSON Tree verstehe ist das auch im iobroker bisher nicht drin.
