### ISSUE TITLE
Saving device config

### ISSUE THREAD

**Issue by fzzybllz** [Zefau/ioBroker.jarvis#22]
Changes to a device configuration aren't saved if you quit the pop-up by using the "save" button on the right. You have to save it with the hook on the left side.

Maybe you can either block the save button or make it save the changes anyways.

**Comment by Zefau** [comment]
Could you try and install v0.2.0 from Github ? The devices screen has been reworked. Adding, editing and saving should work now as expected. Thanks.

**Comment by Zefau** [comment]
@fzzybllz

**Comment by fzzybllz** [comment]
@Zefau will try it next week. thanks

**Comment by Zefau** [comment]
@fzzybllz I will close this for now.

Please see https://github.com/Zefau/ioBroker.jarvis/issues/26, which introduces a new layout structure as well as https://github.com/Zefau/ioBroker.jarvis/issues/21, which introduces a new device structure. Both can be configured via the user interface now (as well as still as json).

These most likely have been all breaking changes, which is why I labeled the latest release with `v1.0.0-alpha.1`.

I would much appreciate if you join testing.

**Comment by Zefau** [comment]
71dbd01dbbe39b7712e168c9058a01c6926f6bf0
