### ISSUE TITLE
[3.2.0-beta.67] scripts-Datei wird nicht gefunden unter user

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2782]
https://github.com/Zefau/ioBroker.jarvis/issues/2716#issuecomment-2308952519

Setze ich eine scripts-Datei hier displayMark.js in 
`/opt/iobroker/node_modules/iobroker.jarvis/www/jarvis/user`
mache ein Upload von jarvis -> `iob upload jarvis` erscheint die Datei auch unter Dateien
![image](https://github.com/user-attachments/assets/48805b95-1259-4180-874a-f71543277944)
Rufe ich sie nun auf mit
`@import "https://192.168.178.150:8400/user/displayMark.js";`

und starte jarvis bekomme ich den Fehler
![image](https://github.com/user-attachments/assets/0683ad5e-5e5d-4e41-b59d-e5c7d820cf18)

Für die Datei wurde auch der user  auf iobroker geändert mit `sudo chown -R iobroker:iobroker ./user`
und dann der upload gemacht.
![image](https://github.com/user-attachments/assets/d0d80c98-b1e0-49b8-bc95-413f71c00fe2)

Wenn ich allerdings die Datei im Browser aufrufe ist sie erreichbar.
![image](https://github.com/user-attachments/assets/6f676954-e045-4e87-a396-3a0bf781cf68)

![image](https://github.com/user-attachments/assets/518dc467-cf1c-4fdd-b94f-ad244efaef13)
Hängt anscheinend mit dem angehängten ?ts=... zusammen
![image](https://github.com/user-attachments/assets/60719bda-5300-4806-a42c-42db2c9a40b0)

Ist die IP beim import eine andere als der Server kann man ?ts0.... anhängen, bei gleicher IP nicht.

**Comment by Zefau** [comment]
Ich hab `eraseOnUpload` mit der nächsten beta abgestellt, d.h. die benutzerspezifischen Skripte sollten damit nicht mehr gelöscht werden.

**Comment by mcuiobroker** [comment]
Wie werden dann Änderungen erkannt?

**Comment by Zefau** [comment]
So wie bisher auch. Bisher war es nur so, dass alte Dateien gelöscht werden, damit die Ordner-Struktur nicht vollgemüllt wird (da sich die Hashes ja immer ändern, also statt `index-96edf5db.js` dann `index-abcdef123.js`). Dies hab ich nun manuell implementiert. Dadurch bleiben die Dateien in `user` erhalten, aber alte jarvis Dateien werden gelöscht.

**Comment by Zefau** [comment]
Mit der nächsten beta müssen die benutzerspezifischen Dateien unter `/opt/iobroker/node_modules/iobroker.jarvis/www/user` abgelegt werden. Ein Upload ist nicht mehr notwendig.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.68` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.68` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
![image](https://github.com/user-attachments/assets/e841ee0b-3b7b-4a63-8280-a73b72166c47)

**Comment by Zefau** [comment]
Nochmal uploaden?

**Comment by mcuiobroker** [comment]
/user Inhalt wird nicht automatisch upgedatet , F5 reicht nicht
![image](https://github.com/user-attachments/assets/a648384f-48dd-40f6-ab7a-105ddbc8355e)

**Comment by mcuiobroker** [comment]
> Nochmal uploaden?

Du meinst die /user -Daten?

**Comment by Zefau** [comment]
> Verzeichnis /user wird bei jedem Upgrade gelöscht

Wo hast du das Verzeichnis denn angelegt?

**Comment by mcuiobroker** [comment]
`/opt/iobroker/node_modules/iobroker.jarvis/www/user`

**Comment by Zefau** [comment]
Jo, das ist richtig. Und der Ordner wird gelöscht?

**Comment by Zefau** [comment]
Ach, sorry, wird beim Upgrade gelöscht. Jo, Mist, das macht ioBroker... daran hab ich wieder nicht gedacht.

**Comment by mcuiobroker** [comment]
Kann man da mit symlinks arbeiten?
`ln -s quelle ziel`

**Comment by mcuiobroker** [comment]
![image](https://github.com/user-attachments/assets/2bbda182-76e1-4cba-aad4-b93570342455)
Hierfür hilft kein Upload

**Comment by Zefau** [comment]
Ist denn `/opt/iobroker/iobroker-data/files/0_userdata.0` ein "offizielles" Verzeichnis?

**Comment by mcuiobroker** [comment]
Ja

**Comment by Zefau** [comment]
Pfad wird dann mit der nächsten beta `0_userdata.0/jarvis-scripts` sein.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.70` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.70` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Änderungen bei Dateien unter `/jarvis-scripts` werden nicht erkannt. 
Man muss jarvis-Instanz neu starten, damit die Änderungen wirksam werden.

**Comment by Zefau** [comment]
Die Dateien werden bei jedem Start in den Ordner `node_modules/iobroker.jarvis/www/user` übernommen.

**Comment by mcuiobroker** [comment]
Anscheinend nur bei Instanz-Start?

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.71` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.71` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Hat nicht funktioniert . Habe direkt unter files/0_userdata.0/jarvis-scripts/time.js geändert mit dem ioBroker-Editor (Doppelklick auf Datei)
![image](https://github.com/user-attachments/assets/dc503364-c132-471b-a8e0-f40b276bbc01)
![image](https://github.com/user-attachments/assets/a9298b44-5d7b-4873-8e11-697e45dea165)

**Comment by Zefau** [comment]
Also er wird es nicht online aktualisieren. Wenn du es in dem Ordner änderst, dann musst du die Seite neu laden.

**Comment by mcuiobroker** [comment]
Ich ändere in dem Ordner und lade die Seite neu (F5). Es ändert sich aber nichts, bzw. die Änderung in Datei bekommt er nicht mit.

**Comment by Zefau** [comment]
Jo, ok, das ist falsch. Änderungen sollten ohne Neustart, aber mit einem Reload der Seite sichtbar sein.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.72` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.72` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Funktioniert. Danke.

**Comment by mcuiobroker** [comment]
Zu früh gefreut.
Anscheinend gibt doch noch Probleme.

**Comment by Zefau** [comment]
Jo, stimmt, die Scripte werden gecached. hmpf, ohne Cache dauert das initiale Laden länger.

**Comment by mcuiobroker** [comment]
Das sind ms, das merkt man nicht

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.73` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.73` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
werden gar nicht mehr geladen

**Comment by Bernd9000** [comment]
Kleine Zwischenfrage :-)
Wollte von `v3.2.0-beta.6` auf `v3.2.0-beta.73` gehen.
jarvis startet nicht mehr und ich krieg folgende Meldungen.
Was muß ich jetzt mit vorhandenen scripten machen damit jarvis wieder startet ?

iob Host Warnung:

![1](https://github.com/user-attachments/assets/f7620612-07a0-414a-b97b-5b91fac4780d)

iob Log:

`<html><body>

host.ServerSmartHome) | 2024-09-11 12:11:44.682 | warn | host.Server(SmartHome) Do not restart adapter system.adapter.jarvis.0 because restart loop detected
-- | -- | -- | --
host.ServerSmartHome) | 2024-09-11 12:11:44.682 | info | host.Server(SmartHome) Restart adapter system.adapter.jarvis.0 because enabled
host.ServerSmartHome) | 2024-09-11 12:11:44.682 | error | host.Server(SmartHome) instance system.adapter.jarvis.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
jarvis.0 | 2024-09-11 12:11:44.409 | info | terminating
jarvis.0 | 2024-09-11 12:11:43.893 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
jarvis.0 | 2024-09-11 12:11:43.892 | info | terminating
jarvis.0 | 2024-09-11 12:11:43.891 | info | Adapter stopped und unloaded.
jarvis.0 | 2024-09-11 12:11:43.877 | warn | Failed  moving user scripts due to "ENOENT: no such file or directory, lstat  'C:\Software\ioBroker\iobroker-data\files\0_userdata.0\jarvis-scripts'"!
jarvis.0 | 2024-09-11 12:11:43.875 | error | Exception-Code:  ENOENT: ENOENT: no such file or directory, watch  'C:\Software\ioBroker\node_modules\iobroker.jarvis/../../iobroker-data/files/0_userdata.0/jarvis-scripts'
jarvis.0 | 2024-09-11 12:11:43.874 | error | Error:  ENOENT: no such file or directory, watch  'C:\Software\ioBroker\node_modules\iobroker.jarvis/../../iobroker-data/files/0_userdata.0/jarvis-scripts'     at FSWatcher.<computed> (node:internal/fs/watchers:247:19)     at watch (node:fs:2491:36)    at JarvisServer.init  (C:\Software\ioBroker\node_modules\iobroker.jarvis\lib\jarvis.server.js:1:2258)     at  C:\Software\ioBroker\node_modules\iobroker.jarvis\jarvis.min.js:1:2631
jarvis.0 | 2024-09-11 12:11:43.873 | error | unhandled  promise rejection: ENOENT: no such file or directory, watch  'C:\Software\ioBroker\node_modules\iobroker.jarvis/../../iobroker-data/files/0_userdata.0/jarvis-scripts'
jarvis.0 | 2024-09-11 12:11:43.872 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
jarvis.0 | 2024-09-11 12:11:43.837 | info | starting.  Version 3.2.0-beta.72 (non-npm:  Zefau/ioBroker.jarvis#3b70f52cf5c5caf6834b4fd38a37f8302adcfb3f) in  C:/Software/ioBroker/node_modules/iobroker.jarvis, node: v20.17.0,  js-controller: 6.0.11


</body>
</html>`

**Comment by mcuiobroker** [comment]
@Bernd9000 
Verzeichnis `jarvis-scripts` unter files/0_userdata.0 anlegen
![image](https://github.com/user-attachments/assets/30e2ca90-e9a0-41e4-a088-38d323e6c96d)
Läuft aber momentan nicht mit beta.73, nur mit btea.72

**Comment by Bernd9000** [comment]
Okay, Danke.
Jetzt startet jarvis wieder, aber jarvis wurde irgendwie zurückgesetzt, alle Einstellungen weg.
Ich warte mal weiter ab.....

**Comment by mcuiobroker** [comment]
Welche Einstellungen? Bzgl scripts.

**Comment by Bernd9000** [comment]
`widgets` und `layout` wurden gelöscht in der iob Datenbank.
Nur noch die Geräte in `devices` sind vorhanden.
Ist nur ein Testsystem, wie gesagt, ich warte ab bis das mit den scripten funktioniert und dann teste ich nochmal.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.74` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.74` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Zefau** [comment]
Zum Verständnis: Du änderst den Skript-Input in jarvis nicht, richtig? Dort hast du quasi nur einen `import`. Der `import` verweist auf eine Datei, die du dann außerhalb von jarvis in einem Editor anpasst. Nach der Anpassung machst du einen Reload der Seite, aber deine Anpassungen werden nicht übernommen.

Im Cache befindet sich nämlich nur der Skript-Input, keine externen Dateien.
Wenn du die Datei normal im Browser per URL aufrufst, wird dort der aktuelle Stand dargestellt?

**Comment by mcuiobroker** [comment]
>Zum Verständnis: Du änderst den Skript-Input in jarvis nicht, richtig?

Richtig. Ja nur einen @import

Verweisen nur noch auf z.B. `@import "https://192.168.178.150:8400/user/jarvisDPs.js";`
`@import "https://192.168.178.150:8400/user/timer.js";`

Dann ändere ich die Datei timer.js im Ordner `/opt/iobroker/iobroker-data/files/0_userdata.0/jarvis-scripts` direkt in iobroker
![image](https://github.com/user-attachments/assets/36c22ae8-16c4-47c9-9e09-0ebafb2bfe09)
Doppelklick auf die Datei timer.js , dann ändern und Speichern.
Dies funktioniert nach Löschen von den Browserdaten genau einmal, dann nicht mehr.

**Comment by Zefau** [comment]
Du änderst in ioBroker? Wenn ich es direkt auf dem Fileserver ändere geht es bei mir.

**Comment by mcuiobroker** [comment]
Ja in iobroker -> Dateien und in dem definierten Verzeichnis. Doppelklick auf Datei.
![image](https://github.com/user-attachments/assets/929a9b76-e093-4154-8101-c72c66597706)

**Comment by Zefau** [comment]
Ich meinte den ioBroker-Server mit File-Server. Du kannst den ja per Samba oder NFS einbinden und die Dateien direkt im Verzeichnis ohne ioBroker ändern.

Ist aber egal wie man es macht, bei mir geht es.

![2782](https://github.com/user-attachments/assets/0061d389-ff03-439f-bed9-b9f280c3cfe4)


![grafik](https://github.com/user-attachments/assets/5b3efa3d-3c66-487f-a9d1-dcb22d3c191c)

**Comment by mcuiobroker** [comment]
Nicht 8089 nutzen 8400

**Comment by mcuiobroker** [comment]
Nach oben scrollen , sonst sieht man nicht alles
![scripts-ProblemSpeicher1](https://github.com/user-attachments/assets/d27621e8-8599-4457-9113-adb3dc1dfee0)

**Comment by mcuiobroker** [comment]
Jetzt nach ca 3-5Minuten Warten, wurde die Datei anscheinend aktualisiert. Warum auch immer.
Also Date geändert
3-5 min Warten
F5  -> geänderte Daten sichtbar

**Comment by Zefau** [comment]
Die Version `v3.2.0-rc.1` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-rc.1` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Sieht gut aus. Danke.
