### ISSUE TITLE
Add pre-defined layout and devices based on user-defined enums

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#31]
Supported adapters and device types:

| Adapter | `light` | `blinds` | `socket` | `heating` |
| --------- |:------:|:--------:|:--------:|:----------:|
| deconz | x | | x |
 | hue | x | | x |
| hue-extended | x | | x |
| shelly | x | x | x |
| HomeMatic IP | x | x | x | x |

**Comment by braindead1** [comment]
Your idea together with the possibility to automatically import alias devices would really improve and speed up the configuration of jarvis.

![image](https://user-images.githubusercontent.com/2136249/90429557-3d9bf980-e0c6-11ea-88dc-576864cc5bc4.png)

**Comment by Zefau** [comment]
Looks good. How do I activate the alias functionality? Is that a dedicated adapter? Couldn't find one and I'm missing the option in the menu.

**Comment by Zefau** [comment]
@braindead1 Actually looks like that the `alias` devices automatically added to the `enums` as well when assigned to a function?

**Comment by braindead1** [comment]
I just started using the adapter, but during the last ioBroker developer session it was discussed that the adapter could become part of the standard feature set. Therefore it is worth spending time. The intention of the adapter is to create a unified structure for devices of different adapters.

The answer to your question highly depends on the way aliases are created. If the alias is created with the mentioned adapter, the state names are given and cannot be changed by the users. Besides the adapter, aliases can be created manually (e.g. via scripts that can be found in the forum) and here the user is free to name states.

**Comment by Zefau** [comment]
This has been introduced now with `v1.0.0-beta.1` and is ready for testing.

You will find the option to `Import devices` in the Devices tab of the configuration panel, see:
![image](https://user-images.githubusercontent.com/14368811/91656707-1d533e00-eabb-11ea-9ba6-4abf8cbff899.png)

The following adapters are supported for a device import:
![image](https://user-images.githubusercontent.com/14368811/91656731-4378de00-eabb-11ea-8b42-45a77fc26e59.png)


You may either search the whole adapter structure or filter to only search within (the user defined) enums.

**Comment by Zefau** [comment]
@braindead1 I would appreciate if you could test this functionality as well. Thanks for that!

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/41

**Comment by braindead1** [comment]
I removed my complete configuration to simulate a fresh installation of jarvis. I noticed the following:

* The message "Please create the configuration. See documentation" is shown until the configuration is done. It should be possible to close this message manually. The message covers parts of the configuration dialog.

![image](https://user-images.githubusercontent.com/2136249/91660560-fdca0e80-ead6-11ea-9f39-c59c91b26016.png)

* Newly imported devices should be ticked by default. Otherwise the user has to tick every device he wants to import. I have 51 alias devices and this was cumbersome.

* All imported lights are handled like dimmers, meaning the `SET` state is transformed into `level`, which is not correct. I have a lot of dimmers, but the same amount of not dimmable lights.

* It should be possible to disable the above mentioned transformation.

* The above mentioned transformation should be improved to also set the `Action` for `SET` / `level`.

Other things I noticed that are not related to device import:

* The "Abbrechen" button next to "Speichern" is pulsating until you click somewhere else. I was not able to take a screenshot to show what I mean as this effect is only available when the browser window has focus.

* Saving "Page Settings" results in the following JSON: `{"[object Object]":"Smart Home"}`. I wanted to set the language to "Deutsch" and the title to "Smart Home".

**Comment by Zefau** [comment]
- [x] The message "Please create the configuration. See documentation" is shown until the configuration is done. It should be possible to close this message manually. The message covers parts of the configuration dialog.
- [ ] Newly imported devices should be ticked by default. Otherwise the user has to tick every device he wants to import. I have 51 alias devices and this was cumbersome.
- [ ] All imported lights are handled like dimmers, meaning the `SET` state is transformed into `level`, which is not correct. I have a lot of dimmers, but the same amount of not dimmable lights.
- [ ] It should be possible to disable the above mentioned transformation.
- [ ] The above mentioned transformation should be improved to also set the `Action` for `SET` / `level`.
- [ ] The "Abbrechen" button next to "Speichern" is pulsating until you click somewhere else. I was not able to take a screenshot to show what I mean as this effect is only available when the browser window has focus.
- [x] Saving "Page Settings" results in the following JSON: `{"[object Object]":"Smart Home"}`. I wanted to set the language to "Deutsch" and the title to "Smart Home".

**Comment by Zefau** [comment]
It will not be possible to disable the state transformation. The created states can easily be removed. Furthermore, the "original" states will always be created / adapted as well.

**Comment by Zefau** [comment]
This should be resolved with `1.0.0-beta.2` respectively `1.0.0-beta.8`.

**Comment by Zefau** [comment]
>  The "Abbrechen" button next to "Speichern" is pulsating until you click somewhere else. I was not able to take a screenshot to show what I mean as this effect is only available when the browser window has focus.

Could you explain in detail how to reproduce this? You are on the Device Import dialogue and you have searched for devices already and seeing the result list? And having the browser window focused the "Abbrechen" button is pulsating?

**Comment by braindead1** [comment]
I have a clean installation of `v1.0.0-beta.8` and no configuration. The config dialogue pops-up and now the "Abbrechen" button is pulsating until you click somewhere else. I tried Google Chrome and Microsoft Edge. In both browsers it's the same.

![image](https://user-images.githubusercontent.com/2136249/92284304-00c36580-ef02-11ea-8a39-a7c25885608c.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/51

**Comment by Zefau** [comment]
aa13283a3eac314bd9a01ae3f0d2f86ae37a68b3
