### ISSUE TITLE
Support of Yeelight devices in the importer

### ISSUE THREAD

**Issue by macstone23** [Zefau/ioBroker.jarvis#593]
It would be great to have support for Yeelight devices.

<img width="1163" alt="Yeelight-Lampe1" src="https://user-images.githubusercontent.com/68864439/104186295-827a5100-5416-11eb-830b-76d79d868f59.png">
<img width="1171" alt="Yeelight-Lampe2" src="https://user-images.githubusercontent.com/68864439/104186321-8908c880-5416-11eb-8eac-af2f3051beec.png">

**Comment by Zefau** [comment]
ca 2.054 user

**Comment by Zefau** [comment]
@macstone23 added with `v2.2.0-beta.14`.

**Comment by SevenUp666** [comment]
funktioniert bei mir leider nicht
Wird im Importer zwar angezeigt, aber die Suche (Adapter lesen) dauert ewig und kommt zu keinem Ergebnis.

**Comment by Zefau** [comment]
Erscheint ein Fehler in der Browser Konsole?

**Comment by SevenUp666** [comment]
habe bisher nur im ioBroker Log im Debug Mode geschaut, da war nichts.

In der Broweser Console aber schon:
`Log.js:56 App # Welcome to jarvis 2.2.0-beta.14
Log.js:56 App # You are on instance jarvis.0.
Connection.js:58 Connecting to http://192.168.1.240:8082 ..
Connection.js:62 Connected to http://192.168.1.240:8082.
Log.js:56 App # Processed 235 devices and discarded 0 devices due to incorrect configuration. See browser console log for more details:  {devices: {…}, states: Array(1231), processedDevices: 235, addedDevices: 235, ignoredDevices: 0, …}
Log.js:56 Devices # Es konnten keine Adapter Geräte, Kanäle oder Datenpunkte geladen werden!
value @ Log.js:56
(anonymous) @ Devices.js:170
Promise.catch (async)
(anonymous) @ Devices.js:168
(anonymous) @ Devices.js:133
value @ Devices.js:131
onClick @ ImportDevicesPage.js:243
s @ react-dom.production.min.js:14
h @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
v @ react-dom.production.min.js:15
ot @ react-dom.production.min.js:52
rt @ react-dom.production.min.js:51
st @ react-dom.production.min.js:52
ht @ react-dom.production.min.js:56
I @ react-dom.production.min.js:287
F @ react-dom.production.min.js:19
Jt @ react-dom.production.min.js:70
Zt @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
N @ react-dom.production.min.js:287
$t @ react-dom.production.min.js:68
Log.js:56 ImportDevicesPage # IMPORT_DEVICES: Cannot read property 'value' of undefined
value @ Log.js:56
(anonymous) @ ImportDevicesPage.js:246
Promise.catch (async)
onClick @ ImportDevicesPage.js:245
s @ react-dom.production.min.js:14
h @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
v @ react-dom.production.min.js:15
ot @ react-dom.production.min.js:52
rt @ react-dom.production.min.js:51
st @ react-dom.production.min.js:52
ht @ react-dom.production.min.js:56
I @ react-dom.production.min.js:287
F @ react-dom.production.min.js:19
Jt @ react-dom.production.min.js:70
Zt @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
N @ react-dom.production.min.js:287
$t @ react-dom.production.min.js:68`

**Comment by Zefau** [comment]
kannst du mir mal deine Objekt-Struktur von Yeelight exportieren?

**Comment by SevenUp666** [comment]
läuft nun durch, findet aber nichts.
[Objekt-Struktur]https://filehorst.de/d/dIxilgum)
[LOG](https://filehorst.de/d/dFcFEkzJ)

**Comment by Zefau** [comment]
Mit `v2.2.0-beta.17` sollte es nun passen

**Comment by SevenUp666** [comment]
Danke. Läuft nun zügig durch und findet auch die Geräte.
Die Namen werden von ioBroker aber nicht übernommen:
[![Bild 2021-01-1622_07_21-scjbi.png auf abload.de](https://abload.de/img/2021-01-1622_07_21-scjbi.png)](https://abload.de/image.php?img=2021-01-1622_07_21-scjbi.png)

Kleiner Fehler, oder geht nicht anders?

**Comment by Zefau** [comment]
Wo steht denn der Name? jarvis übernimmt die Spalte "Name":

![image](https://user-images.githubusercontent.com/14368811/104823262-392c6600-5849-11eb-901c-6cf79e4136f7.png)

**Comment by SevenUp666** [comment]
Hast recht.
Ist dann eher so, dass Yeelight-Adapter war den Namen aus Yeelight-App als device-Knoten übernommen hat, aber nicht als "Name".

--> Jarvis macht mit Yeelight also nun alles richtig
