### ISSUE TITLE
v3: Bei der Konvertierung wird der Wert für das Objekt in der JSONtable nicht mit übernommen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#781]
![image](https://user-images.githubusercontent.com/84818934/120933733-bde62680-c6fb-11eb-981c-8ff60e4989ae.png)
So hätte es aussehen sollen:
![image](https://user-images.githubusercontent.com/84818934/120933751-cdfe0600-c6fb-11eb-864d-ba61bd09874e.png)

**Comment by Zefau** [comment]
Fixed with `v3.0.0-alpha.7`

ACHTUNG: Bitte nochmal jarvis neu konvertieren lassen.

Dazu:
1. Alle jarvis Instanzen schließen und Adapter stoppen
2. `jarvis.0.layout` und `jarvis.0.devices` mit den v2 Daten befüllen
3. `jarvis.0.widgets` auf `{}` leer machen
4. jarvis Adapter starten und jarvis aufrufen
5. Blick in die Browser-Konsole, ob es zu einem Fehler kam

**Comment by mcuiobroker** [comment]
Sieht gut aus

**Comment by mcuiobroker** [comment]
Ich sollte ja nach Meldungen schauen, hatte ich bis jetzt vergessen:
Nur zur Info:
![image](https://user-images.githubusercontent.com/84818934/121819293-8abc0e00-cc8c-11eb-9642-9848dfbaee68.png)

**Comment by Zefau** [comment]
Die ersten beiden Screenshots sind "fremde" Meldungen (wegen iFrame sicherlich?)

Das mit den Fonts ist leider so. Das bekomme ich nicht weg. Mal schauen, ob ich das nun dank Iconify wieder abschalten kann.

Ich schließe das Ticket mal, da der originäre Fehler mit dem JSONTable behoben ist.
